#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
# 1.The path to the file to be transferred
# 2.The IP of the server we want to transfer the file to
# 3.The username scp connects with
# 4.The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	server_ip=$2
	username=$3
	ssh_path_key=$4
	
	scp -o StrictHostKeyChecking=no -i "$ssh_path_key" "$file_path" "$username@$server_ip":~/
fi
